// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkKff_r4Lk_QB2Fz1fgptMWv75SZi9aQc',
    appId: '1:242236946482:web:3d5df9d76256a26d16a42b',
    messagingSenderId: '242236946482',
    projectId: 'hr-connect-e46cb',
    authDomain: 'hr-connect-e46cb.firebaseapp.com',
    storageBucket: 'hr-connect-e46cb.firebasestorage.app',
    measurementId: 'G-7H2X3J1CQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIGcPVKvBc9Ub-lXcXrYjNGn85cvcAc4',
    appId: '1:242236946482:android:b67726724df909ec16a42b',
    messagingSenderId: '242236946482',
    projectId: 'hr-connect-e46cb',
    storageBucket: 'hr-connect-e46cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQGE6oW4AG2rAexvOKspdOwOxsQb0KEc',
    appId: '1:242236946482:ios:aabf3748d9b58bda16a42b',
    messagingSenderId: '242236946482',
    projectId: 'hr-connect-e46cb',
    storageBucket: 'hr-connect-e46cb.firebasestorage.app',
    iosBundleId: 'com.example.hrConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQGE6oW4AG2rAexvOKspdOwOxsQb0KEc',
    appId: '1:242236946482:ios:aabf3748d9b58bda16a42b',
    messagingSenderId: '242236946482',
    projectId: 'hr-connect-e46cb',
    storageBucket: 'hr-connect-e46cb.firebasestorage.app',
    iosBundleId: 'com.example.hrConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkKff_r4Lk_QB2Fz1fgptMWv75SZi9aQc',
    appId: '1:242236946482:web:c9e28a24022ac13816a42b',
    messagingSenderId: '242236946482',
    projectId: 'hr-connect-e46cb',
    authDomain: 'hr-connect-e46cb.firebaseapp.com',
    storageBucket: 'hr-connect-e46cb.firebasestorage.app',
    measurementId: 'G-LCYFTJZY1B',
  );

}