import 'package:hr_connect/core/const/enums.dart';
import 'package:hr_connect/features/user_management/data/models/user_model.dart';

class UserData {
  static final Map<String, UserModel> dummyUsers = {
    'USR-001': UserModel(
      uid: 'USR-001',
      firstName: 'Hafizryandin',
      lastName: 'Haykal Matondang',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=1',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
    'USR-002': UserModel(
      uid: 'USR-002',
      firstName: 'Muhammad Fathir',
      lastName: 'Rizky Salam',
      role: UserRole.director,
      avatarUrl: 'https://i.pravatar.cc/150?img=2',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 22)),
      updatedAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
    'USR-003': UserModel(
      uid: 'USR-003',
      firstName: 'Hafidz Naufal',
      lastName: 'Pradana',
      role: UserRole.manager,
      avatarUrl: 'https://i.pravatar.cc/150?img=3',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 12)),
    ),
    'USR-004': UserModel(
      uid: 'USR-004',
      firstName: 'Haidar Zahran',
      lastName: 'Haryono',
      role: UserRole.supervisor,
      avatarUrl: 'https://i.pravatar.cc/150?img=4',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now().subtract(const Duration(days: 11)),
    ),
    'USR-005': UserModel(
      uid: 'USR-005',
      firstName: 'Cecep Wijaya',
      lastName: 'Antonio Lopez',
      role: UserRole.staff,
      avatarUrl: 'https://i.pravatar.cc/150?img=5',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-006': UserModel(
      uid: 'USR-006',
      firstName: 'Test 1',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=6',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-007': UserModel(
      uid: 'USR-006',
      firstName: 'Test 2',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=7',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-008': UserModel(
      uid: 'USR-006',
      firstName: 'Test 3',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=8',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-009': UserModel(
      uid: 'USR-006',
      firstName: 'Test 4',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=9',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-010': UserModel(
      uid: 'USR-006',
      firstName: 'Test 5',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=10',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-011': UserModel(
      uid: 'USR-0006',
      firstName: 'Test 6',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=11',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    'USR-012': UserModel(
      uid: 'USR-0006',
      firstName: 'Test 7',
      lastName: 'System',
      role: UserRole.admin,
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
  };
}
