name: Flutter Apk

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Setup .env file
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          echo "BASE_URL=$BASE_URL" > .env
          echo "PHASE=production" >> .env

      - name: Analyze code (Linting)
        run: flutter analyze

      # - name: Run Unit Tests
      #   run: flutter test

      - name: Build Release APK (Android Package)
        run: flutter build apk --release

      - name: Build Release AAB (Android App Bundle)
        run: flutter build appbundle --release

      - name: Deploy to Github Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
